#  Project : Logistic Regression

In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv('c:\Users\Kishore\Desktop\Datasets\Social_Network_Ads.csv')

In [3]:
data.head()

User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [91]:
data.tail()

User ID  Gender  Age  EstimatedSalary  Purchased
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

In [93]:
X = data.iloc[:,[2,3]]
Y = data.iloc[:,4]

In [94]:
from sklearn.model_selection import train_test_split

In [95]:
x_train,x_test,y_train,y_test = train_test_split(X , Y ,test_size =0.25 ,random_state = 0)

In [96]:
x_train

Age  EstimatedSalary
250   44            39000
63    32           120000
312   38            50000
159   32           135000
283   52            21000
340   53           104000
81    39            42000
349   38            61000
153   36            50000
295   36            63000
96    35            25000
89    35            50000
296   42            73000
21    47            49000
365   59            29000
216   49            65000
259   45           131000
49    31            89000
238   46            82000
343   47            51000
92    26            15000
223   60           102000
234   38           112000
232   40           107000
377   42            53000
142   35            59000
22    48            41000
252   48           134000
350   38           113000
168   29           148000
..   ...              ...
243   56           104000
115   40            57000
265   42           108000
72    20            23000
333   40            65000
25    47            20000
165   18            86000
337   35            79000
384   57            33000
174   34            72000
386   49            39000
39    27            31000
193   19            70000
314   39            79000
88    26            81000
70    25            80000
87    28            85000
292   55            39000
242   50            88000
277   49            88000
211   52           150000
9     35            65000
359   42            54000
195   34            43000
251   37            52000
323   48            30000
192   29            43000
117   36            52000
47    27            54000
172   26           118000

[300 rows x 2 columns]

In [97]:
x_test

Age  EstimatedSalary
132   30            87000
309   38            50000
341   35            75000
196   30            79000
246   35            50000
60    27            20000
155   31            15000
261   36           144000
141   18            68000
214   47            43000
37    30            49000
134   28            55000
113   37            55000
348   39            77000
12    20            86000
59    32           117000
293   37            77000
140   19            85000
206   55           130000
199   35            22000
176   35            47000
268   47           144000
124   41            51000
344   47           105000
175   23            28000
313   49           141000
78    28            87000
15    29            80000
286   37            62000
102   32            86000
..   ...              ...
7     32           150000
260   35            77000
68    22            63000
20    45            22000
107   27            89000
14    18            82000
363   42            79000
304   40            60000
361   53            34000
329   47           107000
336   58           144000
64    59            83000
55    24            55000
106   26            35000
300   58            38000
229   42            80000
122   40            75000
373   59           130000
395   46            41000
325   41            60000
380   42            64000
253   37           146000
56    23            48000
8     25            33000
190   24            84000
146   27            96000
135   23            63000
390   48            33000
264   48            90000
364   42           104000

[100 rows x 2 columns]

In [98]:
from sklearn.preprocessing import StandardScaler

In [99]:
sc = StandardScaler()

In [100]:
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)


In [101]:
x_train

array([[ 0.58164944, -0.88670699],
       [-0.60673761,  1.46173768],
       [-0.01254409, -0.5677824 ],
       [-0.60673761,  1.89663484],
       [ 1.37390747, -1.40858358],
       [ 1.47293972,  0.99784738],
       [ 0.08648817, -0.79972756],
       [-0.01254409, -0.24885782],
       [-0.21060859, -0.5677824 ],
       [-0.21060859, -0.19087153],
       [-0.30964085, -1.29261101],
       [-0.30964085, -0.5677824 ],
       [ 0.38358493,  0.09905991],
       [ 0.8787462 , -0.59677555],
       [ 2.06713324, -1.17663843],
       [ 1.07681071, -0.13288524],
       [ 0.68068169,  1.78066227],
       [-0.70576986,  0.56295021],
       [ 0.77971394,  0.35999821],
       [ 0.8787462 , -0.53878926],
       [-1.20093113, -1.58254245],
       [ 2.1661655 ,  0.93986109],
       [-0.01254409,  1.22979253],
       [ 0.18552042,  1.08482681],
       [ 0.38358493, -0.48080297],
       [-0.30964085, -0.30684411],
       [ 0.97777845, -0.8287207 ],
       [ 0.97777845,  1.8676417 ],
       [-0.01254409,

In [102]:
x_test

array([[-0.80480212,  0.50496393],
       [-0.01254409, -0.5677824 ],
       [-0.30964085,  0.1570462 ],
       [-0.80480212,  0.27301877],
       [-0.30964085, -0.5677824 ],
       [-1.10189888, -1.43757673],
       [-0.70576986, -1.58254245],
       [-0.21060859,  2.15757314],
       [-1.99318916, -0.04590581],
       [ 0.8787462 , -0.77073441],
       [-0.80480212, -0.59677555],
       [-1.00286662, -0.42281668],
       [-0.11157634, -0.42281668],
       [ 0.08648817,  0.21503249],
       [-1.79512465,  0.47597078],
       [-0.60673761,  1.37475825],
       [-0.11157634,  0.21503249],
       [-1.89415691,  0.44697764],
       [ 1.67100423,  1.75166912],
       [-0.30964085, -1.37959044],
       [-0.30964085, -0.65476184],
       [ 0.8787462 ,  2.15757314],
       [ 0.28455268, -0.53878926],
       [ 0.8787462 ,  1.02684052],
       [-1.49802789, -1.20563157],
       [ 1.07681071,  2.07059371],
       [-1.00286662,  0.50496393],
       [-0.90383437,  0.30201192],
       [-0.11157634,

In [103]:
from sklearn.linear_model import LogisticRegression

In [104]:
classifier = LogisticRegression(random_state =0)

In [105]:
classifier.fit(x_train,y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [106]:
y_pred = classifier.predict(x_test)

In [107]:
y_pred

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0,
       0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 1, 1], dtype=int64)

In [108]:
from sklearn.metrics import confusion_matrix,classification_report,accuracy_score

In [109]:
cm = confusion_matrix(y_test,y_pred)

In [110]:
cm

array([[65,  3],
       [ 8, 24]], dtype=int64)

In [111]:
report = classification_report(y_test,y_pred)

In [112]:
print(report)

             precision    recall  f1-score   support

          0       0.89      0.96      0.92        68
          1       0.89      0.75      0.81        32

avg / total       0.89      0.89      0.89       100



In [113]:
acc = accuracy_score(y_test,y_pred)

In [114]:
acc

0.89000000000000001